### ISSUE TITLE
cholesterol stereochemistry wrong

### ISSUE THREAD

**Issue by TBGAnsell** [owenvickery/cg2at#12]
Hi Owen,

CG2AT is consistently building the wrong stereochemistry of cholesterol molecules on the carbon which the hydroxy group is attached to. It seems to happen in ~50% of molecules so my guess is that the face assignment is random but not corrected in simulation so I think the .itp file is wrong for CHARMM36. The hydroxyl group should be on the same face as the methyl groups. 

Many thanks for your help,

Bertie

**Comment by owenvickery** [comment]
ah seems as though a couple of top files were missing for the CHOL residue. I've added them to the missing fragment databases and I've also added a chiral check to that fragment. 
Give it a try, I cannot check at the moment as I don't have any systems containing CHOL.

**Comment by TBGAnsell** [comment]
Dear Owen, I have tested both the CHARMM36 - Mar2019 and -Jul2020 (updated) versions this morning and both are now correctly building cholesterol. Many thanks for your help.
