### ISSUE TITLE
Adding newest CHARMM36 force field to forcefield folder

### ISSUE THREAD

**Issue by dnusha1994** [owenvickery/cg2at#18]
Hello,

I tried adding the newest CHARMM-36 force field (July 2021) ported for GROMACS to the force field folder and running cg2at2 - when I do this, the program throws up the following error:

Issue finding information for residue:  ALA
There is a issue with: 
/home/dhanushkaw/Downloads/Backmapping/cg2at/database/forcefields/charmm36-jul2021.ff/silicates.rtp

Thanks!

**Comment by owenvickery** [comment]
Sorry for the slow reply. The script now works with the latest charmm36 forcefield. I've added both the base version and the LJPME  version to the forcefield list. 

They correspond to the martini_3-0_charmm36_jul2021 fragments

They have changed the atomtypes of water so I've just added OW and HW back into the atomtypes.atp files.

**Comment by dnusha1994** [comment]
Hi Owen, no worries at all I saw in other posts that you are doing this in your spare time, so I really appreciate it!

Just one thing, I am currently backmapping a Martini 2.2 system back to aa level - would I be able to modify the conversions to work for Martini 2.2?

Best wishes,
Dhanushka

**Comment by owenvickery** [comment]
There was a slight error in yesterdays push, but is fixed now. 

I've added a martini 2.2 fragment database for the latest charmm36 forcefield.

To modify the fragments databases is relatively simply, it is mostly a copy and paste. the new charmm36 Jul2021 doesn't have the modified protein residues so I have just removed them from the fragment database. The rest is the same.
