### ISSUE TITLE
Ring conformation of PIP2 lipids wrong

### ISSUE THREAD

**Issue by LHRK** [owenvickery/cg2at#19]
Hi, 
I am currently trying to backmap martini 3 PI(3,4)P2 lipids from Martini 3 to Charmm36, and the ring conformation is messed up. The alcohol at 2' should be axial, while the two other alcohols at 6' and 5' should be equatorial, the same with the PO4 group in the linker region. This is sadly not the case. 

I have tried adding some improper dihedrals in the atomistic itp -> didn't work
I have tried added a top file with chirality of the 6 carbons in the ring -> almost worked, but not entirely. 
The H1 (hydrogen of the 1' position) should be flipped 180. 
Maybe I don't entirely understand how the format of the top file works. 
What I tried was : 

 [ GROUPS ]
C1 C2 C3 P3 P4 P04 
[ CHIRAL ]
column must be in the order:
central atom, atom to move, atom_1, atom_2, atom_3

C11 H1 O12 C16 C12
C12 H2 O2  C11 C13
C13 H3 O3  C12 C14
C14 H4 O4  C15 C13
C15 H5 O5  C14 C16
C16 H6 O6  C11 C15

The CG itp is the newest published version of PI(3,4)P2 lipids for martini 3. 

Can you possibly help with this ? 
Best Lisbeth

**Comment by LHRK** [comment]
Here are the files if needed
[SAPC.zip](https://github.com/owenvickery/cg2at/files/9062015/SAPC.zip)

**Comment by owenvickery** [comment]
The conversion of the previous PO version of PI(3,4)P2 conversion were fine.

I'll have a look at the conversion of your files. But typically I wouldn't group the phosphates in with the ring.  

I've not tried with an empty CG bead before will likely have to update the code. 

I'm now working on this in my spare time, so I'll have a look on the weekend.

**Comment by owenvickery** [comment]
Right the main issue was in your fragment file. 

You had one hydrogen from the lipid tail in the head group and a hydrogen from one of the phosphates in the center of the inositol ring.

One thing I noticed was that the chiral checker was only running on the protein, this has been updated to run on the lipids as well now.

The corrected fragment file is in:
"database/fragments/martini_3-0_charmm36_Jul2021/non_protein/SAPC"

Hope this is provides a better output.

**Comment by LHRK** [comment]
Hi !
Thanks! I just tested it now, after having pulled the new code, and the PIP2 lipids are looking good! 
However, I am not able to backmap the protein now, I get KeyError: 'HA'.  I have attached my protein structure.
[Prot.zip](https://github.com/owenvickery/cg2at/files/9191515/Prot.zip)

I think an error occurs when reading the chirality, based on the output I get.

**Comment by owenvickery** [comment]
Ah seems I was over zealous on the chirality checking. I was trying to correct the backbone chirality before the hydrogens were added.
Should all be working now...

**Comment by LHRK** [comment]
Great! 
Protein is correct now as well, thanks!
I only now have problems with the solvent, I get KeyError 'SOL'


Traceback (most recent call last):
   File "/data1/lisbeth/PYTHON/cg2at/cg2at", line 132, in <module>
     number = at_mod_np.build_atomistic_system(residue_type)
   File "/data1/lisbeth/PYTHON/cg2at/database/bin/at_mod_np.py", line
17, in build_atomistic_system
     atomistic_fragments, system[residue_type] =
at_np_solvent(residue_type, g_var.cg_residues[residue_type])
   File "/data1/lisbeth/PYTHON/cg2at/database/bin/at_mod_np.py", line
71, in at_np_solvent
     chiral = at_mod.get_chiral_non_carbonyl(atomistic_fragments[cg_resid])
   File "/data1/lisbeth/PYTHON/cg2at/database/bin/at_mod.py", line 526,
in get_chiral_non_carbonyl
     if at[atom]['atom'] in
g_var.res_top[at[atom]['res_type']]['CHIRAL']['atoms']:
KeyError: 'SOL'


[End_frame_SAPI2C_SAPI2D.zip](https://github.com/owenvickery/cg2at/files/9196847/End_frame_SAPI2C_SAPI2D.zip)

I have attached the file Im trying on. I use the charmm36_ljpme-jul2021

**Comment by owenvickery** [comment]
grr, sorry am trying to fix without any benchmark systems. 

That should be working now.....

**Comment by LHRK** [comment]
Hi again, I just tried, but it complains about an issue with charmm36_ljome-jul2021.ff/solvent.rtp along with issues finding information for residues CYSD. 
Thanks for the help. Let me know if you need anything for me for testing.

**Comment by owenvickery** [comment]
Hi, so I can convert your system, bar the PIP lipids as I don't have the parameters for them. 

I would suggest downloading a fresh version, use git clone as the conda repo is slow to update. Then copy your pip lipids into martini_3-0_charmm36_Jul2021 fragment database. 

The issue with CYSD is that the modified residues don't exist within the forcefield, so comes up with an error.

You can delete the "protein_modified" folder from the fragment folder then it should be fine.

**Comment by LHRK** [comment]
Thanks ! It works excellent for me now.
