### ISSUE TITLE
Unable to backmap simple protein structure

### ISSUE THREAD

**Issue by LHRK** [owenvickery/cg2at#20]
Hi again,
Maybe I am doing something wrong, but I am now encountering a problem of being able to backmap a system with a membrane protein perfectly, however, another system with same membrane and membrane protein, but with an extra peptide, I am no longer able to backmap the protein! 
The membrane is fine, no problem there, but the protein is an issue. 

Can you possibly help?
I have attached the protein CG model.
[Prot.zip](https://github.com/owenvickery/cg2at/files/9222047/Prot.zip)

**Comment by owenvickery** [comment]
Ah, thankfully this isn't a bug in my script rather in the charmm36 forcefield files.

They have changed the c.tbd entry from:
[ COO- ]
....
[ add ]
 2	8	OT	C	CA	N
	OC	15.9994 -0.67	-1
..... 
to:
; CHARMM CTER
[ COO- ]
...
[ add ]
 2	8	OT	C	CA	**CB**
	OC	15.9994 -0.67	-1
...

This cause pdb2gmx to fail as there is no CB atom in your terminal GLY residue.

I've changed their forcefield back to how it was for now. so it will work now.

Cheers
Owen
