### ISSUE TITLE
Bug with program using GROMACS 2022

### ISSUE THREAD

**Issue by dnusha1994** [owenvickery/cg2at#21]
Hi - I found a bug I think in the code when using it with GROMACS 2022. When I run the program, it is making the start terminus of my proteins uncharged and the end terminus charged. I get the same issue when I run it with the -ter flag and choose NH3+ and COO- manually. I also tried applying the script to the tutorial systems provided with the code to be sure that it wasn't a problem with my systems, and I see the same thing.

However if I manually run the pdb2gmx command that the program outputs (with the -ter flag) and select NH3+ and COO-, it does charge both termini as intended so it seems like it may be something to do with the way the GROMACS version interfaces with the program?

**Comment by owenvickery** [comment]
Which forcefield where you trying with? and what were the termini residues?

**Comment by owenvickery** [comment]
Hi, I believe I have fixed this issue, please have a go.
